# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: McpAuth
metadata:
  template: McpAuth@1.0.0
services:
  auth:
    project: ../../auth/
    language: python
    host: function
