# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: McpApp
resourceGroup: gcmdev-mcp2app-dev
metadata:
  template: McpApp@1.0.0
services:
  app:
    project: ../../app/
    language: python
    host: function
